spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle1234
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080
  
# 📄 src/main/resources/application.yml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    map-underscore-to-camel-case: true
